name: upper-capture

on:
    push:
        paths:
            - ".github/workflows/upper-capture.yml"
            - "upper/**"
    workflow_dispatch: #manual trigger

jobs:
    capture:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        defaults:
            run: 
                working-directory: ./upper
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.22.2'
                cache-dependency-path: ./upper/go.sum
            - run: ls
            - run: go build
            - run: ls
            - run: go test -v
            - uses: actions/upload-artifact@v4 
              with:
                path: upper/upper.exe 
                name: "build-${{ matrix.os }}"
            